name: Release
on:
  pull_request_review:
    branches: [release-candidate]
    types: [submitted]

jobs:
  release:
    name: Publish releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Cache npm dependencies
        id: cache-npm-libraries
        uses: actions/cache@v2
        with:
          path: .yarn/cache/*
          key: ${{ runner.os }}
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: corepack yarn install
      - name: Get CHANGELOG
        run: git --no-pager diff HEAD^ -- CHANGELOG.md | awk '{ if( substr($0,0,1) == "+" && $1 != "+##" && $1 != "+Released:" && $1 != "+++" ) { print substr($0,2) } }' > CHANGELOG.next.md
      - name: Publish to NPM
        run: corepack yarn workspaces foreach --no-private npm publish --access public --tolerate-republish
      - name: Merge PR
        id: merge
        run: gh pr merge --squash --body-file CHANGELOG.next.md --delete-branch | jq -r 'if .merged then "##[set-output name=sha;]"+.sha else error("not merged") end'
      - name: Create tags
        run: |
          git --no-pager diff --name-only HEAD^ | grep package.json | awk '{ print "jq -r '"'"'\"gh api /repos/{owner}/{repo}/git/refs -f ref=\\\"refs/tags/\"+.name+\"@\"+.version+\"\\\" -f sha={{ steps.merge.outputs.sha }}\"'"'"' < " $0 }' > createTags.sh
          cat createTags.sh
          sh createTags.sh | sh
      - name: Get Uppy version number
        id: uppyVersion
        run: jq -r '"##[set-output name=version;]"+.version' < packages/uppy/package.json
      - name: Create release
        run: gh release create uppy@{{ steps.uppyVersion.outputs.version }} -t "Uppy {{ steps.uppyVersion.outputs.version }}" -F CHANGELOG.next.md
      - name: Build bundles
        run: corepack yarn run build
      - name: Upload `uppy` to CDN
        run: corepack yarn run uploadcdn uppy
        env:
          EDGLY_KEY: ${{secrets.EDGLY_KEY}}
          EDGLY_SECRET: ${{secrets.EDGLY_SECRET}}
      - name: Upload `@uppy/robodog` to CDN
        run: corepack yarn run uploadcdn @uppy/robodog
        env:
          EDGLY_KEY: ${{secrets.EDGLY_KEY}}
          EDGLY_SECRET: ${{secrets.EDGLY_SECRET}}
      - name: Upload `@uppy/locales` to CDN
        run: corepack yarn run uploadcdn @uppy/locales
        env:
          EDGLY_KEY: ${{secrets.EDGLY_KEY}}
          EDGLY_SECRET: ${{secrets.EDGLY_SECRET}}
